version: '3'
services:
  splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
  app:
    depends_on:
      - splash
    build: .
    container_name: 'post-api-container'
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
