version: '3'
services:
  app:
    build: .
    container_name: 'post-api-container'
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
